[package]
name = "migration_based_concurrent_hashmap"
version = "0.1.0"
edition = "2018"

[dependencies]
arc-swap = "1.3.0"
bitvec = "0.22.3"
init_array = "0.1.2"
static_assertions = "1.1.0"

[dev-dependencies]
assert_matches = "1.5.0"
